-- ---------------------------------------------------------------------------
-- Reference DDL for the order processing system (PostgreSQL flavour).
--
-- This file is documentation + provisioning aid, not the runtime migration path:
--   * local development   : Hibernate derives the schema (spring.jpa.hibernate.ddl-auto=update)
--   * AWS RDS / managed DB: run this script once, then switch JPA_DDL_AUTO to "validate"
--
-- The application never relies on this file for correctness. Every guarantee below is also
-- declared on the JPA entities, so a database created either way behaves identically.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS product (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(160)  NOT NULL,
    price      NUMERIC(12, 2) NOT NULL,
    created_at TIMESTAMP(6)  NOT NULL,
    CONSTRAINT uk_product_name UNIQUE (name),
    CONSTRAINT ck_product_price_non_negative CHECK (price >= 0)
);

-- Stock lives in its own narrow row, one per product: the contended column is separated from the
-- rarely-updated catalogue row, which keeps the pessimistic lock footprint as small as possible.
CREATE TABLE IF NOT EXISTS inventory (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT       NOT NULL,
    quantity   INTEGER      NOT NULL,
    version    BIGINT       NOT NULL DEFAULT 0,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_inventory_product UNIQUE (product_id),
    CONSTRAINT fk_inventory_product FOREIGN KEY (product_id) REFERENCES product (id),
    -- Last line of defence: even a buggy future code path cannot store a negative stock level.
    CONSTRAINT ck_inventory_quantity_non_negative CHECK (quantity >= 0)
);

CREATE TABLE IF NOT EXISTS orders (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id      BIGINT       NOT NULL,
    quantity        INTEGER      NOT NULL,
    status          VARCHAR(20)  NOT NULL,
    retry_count     INTEGER      NOT NULL DEFAULT 0,
    failure_reason  VARCHAR(500),
    idempotency_key VARCHAR(120),
    created_at      TIMESTAMP(6) NOT NULL,
    updated_at      TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_orders_product FOREIGN KEY (product_id) REFERENCES product (id),
    CONSTRAINT uk_orders_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT ck_orders_quantity_positive CHECK (quantity > 0),
    CONSTRAINT ck_orders_retry_count_non_negative CHECK (retry_count >= 0)
);

-- Dashboard summary filters by status, the live table sorts by recency, and per-product analysis
-- walks the foreign key.
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders (status);
CREATE INDEX IF NOT EXISTS idx_orders_product ON orders (product_id);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders (created_at);
